#!/usr/bin/env bash
# Download an object with the AWS CLI using OIDC -> STS (AssumeRoleWithWebIdentity).
#
# Usage:
#   ID_TOKEN=... ./minio_sts_aws_download.sh <bucket> <object-key> [output-file]
#
# Example:
#   ID_TOKEN=... ./minio_sts_aws_download.sh openlat tagtest/test_tagged.txt
#
# Notes:
#   - The RoleARN is generated by the server and can change after a restore, an upgrade or an
#     OpenID change. An administrator can read the current value with: mc idp openid ls ucloud
#     Override it without editing the script:  ROLE_ARN=arn:minio:iam:::role/... ./script ...
#   - The ildg_download policy allows downloads only (no listing), so there is no "aws s3 ls" check.

set -euo pipefail

# ====== CONFIGURATION (override via env) ======
ROLE_ARN="${ROLE_ARN:-arn:minio:iam:::role/6fjOfWNrqjJUCfLsZaCiAD3J8k0}"
MINIO_ENDPOINT="${MINIO_ENDPOINT:-https://app-minio-openlat.cloud.sdu.dk}"
REGION="${REGION:-eu-central-1}"
DURATION="${DURATION:-3600}"
AWS_BIN="${AWS_BIN:-$(command -v aws || echo /usr/local/bin/aws)}"
# ===============================================

if [[ $# -lt 2 ]]; then
  echo "Usage: ID_TOKEN=... $0 <bucket> <object-key> [output-file]" >&2
  exit 1
fi
: "${ID_TOKEN:?Please export ID_TOKEN (your IAM-ILDG token) before running.}"
[[ -x "$AWS_BIN" ]] || { echo "aws CLI not found at $AWS_BIN (set AWS_BIN)" >&2; exit 1; }

BUCKET="$1"
KEY="$2"
OUT="${3:-${KEY##*/}}"

# --- 1. Exchange the OIDC token for temporary credentials ---
echo "→ Requesting STS credentials from ${MINIO_ENDPOINT} ..."
STS_XML="$(curl -sS -X POST "${MINIO_ENDPOINT%/}/" \
  --data-urlencode 'Action=AssumeRoleWithWebIdentity' \
  --data-urlencode 'Version=2011-06-15' \
  --data-urlencode "WebIdentityToken=${ID_TOKEN}" \
  --data-urlencode "DurationSeconds=${DURATION}" \
  --data-urlencode "RoleArn=${ROLE_ARN}")"

extract() { printf '%s' "$STS_XML" | sed -n "s:.*<$1>\\([^<]*\\)</$1>.*:\\1:p"; }
AK="$(extract AccessKeyId)"
SK="$(extract SecretAccessKey)"
ST="$(extract SessionToken)"
EXP="$(extract Expiration)"

if [[ -z "$AK" || -z "$SK" || -z "$ST" ]]; then
  echo "Failed to obtain credentials. Raw response:" >&2
  printf '%s\n' "$STS_XML" >&2
  echo "If the message says the RoleARN is not defined, ask an administrator for the current one." >&2
  exit 1
fi
echo "✓ Got temporary credentials (expire: ${EXP})"

# --- 2. Download in a clean environment so no other AWS credentials are picked up ---
echo "→ Downloading s3://${BUCKET}/${KEY} -> ${OUT}"
if ! env -i \
  AWS_ACCESS_KEY_ID="$AK" \
  AWS_SECRET_ACCESS_KEY="$SK" \
  AWS_SESSION_TOKEN="$ST" \
  AWS_REGION="$REGION" \
  AWS_DEFAULT_REGION="$REGION" \
  AWS_S3_ADDRESSING_STYLE="path" \
  AWS_EC2_METADATA_DISABLED="true" \
  "$AWS_BIN" s3 cp "s3://${BUCKET}/${KEY}" "$OUT" --endpoint-url "$MINIO_ENDPOINT"; then
  echo "Download failed. Possible causes: file not tagged ildg_download=true, wrong path, expired token." >&2
  exit 1
fi

echo "Saved to: ${OUT}"
